# Creates a workflow that will validate and build any protobuf files
# that are in the repository. Protobuf files will automatically be validated
# against the https://api.dev guides for correctness.
name: Protobuf Validation & Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  # Create a new job to lint the protobuf files that are present in the repository. This
  # will fail the build if the protobuf files does not meet the AIP guidelines.
  lint:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup the API Linter tool
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Install API Linter
        run: go get -u github.com/googleapis/api-linter/cmd/api-linter@v1.10.0
      - name: Lint Protobuf Files Summary
        # Run the linter against the StackPath protobuf files and get a summary output
        run: cd schema && api-linter --proto-path=. --proto-path=api-common-protos --output-format=summary $(find stackpath -iname '*.proto')
      - name: Lint Protobuf Files Detail
        # Run the linter against the StackPath protobuf files and get a fully detailed putput in YAML format
        run: cd schema && api-linter --proto-path=. --proto-path=api-common-protos --output-format=yaml $(find stackpath -iname '*.proto')
